apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: aliyun-service
  name: aliyun-service
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: aliyun-service-port
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: aliyun-service
