{
 "title": "aliyun_slb_monitor",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "数据源",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "instance",
    "label": "SLB实例",
    "query": {
     "query": "label_values(metrics_Maximum{origin_prometheus=~\"$origin_prometheus\"}, exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "metrics_Maximum{MetricName=\"MaxConnection\"}",
     "legendFormat": "端口：{{port}}"
    }
   ]
  },
  {
   "title": "活动连接数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "metrics_Maximum{MetricName=\"ActiveConnection\"}",
     "legendFormat": "端口：{{port}}"
    }
   ]
  },
  {
   "title": "带宽使用情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "metrics_Maximum{MetricName=\"TrafficTXNew\"}",
     "legendFormat": "{{port}}端口流出带宽"
    },
    {
     "expr": "metrics_Maximum{MetricName=\"TrafficRXNew\"}",
     "legendFormat": "{{port}}端口流入带宽"
    }
   ]
  },
  {
   "title": "数据包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "metrics_Maximum{MetricName=\"PacketTX\"}",
     "legendFormat": "{{port}}端口流出数据包"
    },
    {
     "expr": "metrics_Maximum{MetricName=\"PacketRX\"}",
     "legendFormat": "{{port}}端口流入数据包"
    }
   ]
  },
  {
   "title": "丢包数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "metrics_Maximum{MetricName=\"DropPacketRX\"}",
     "legendFormat": "{{port}}入口丢包数"
    },
    {
     "expr": "metrics_Maximum{MetricName=\"DropPacketTX\"}",
     "legendFormat": "{{port}}出口丢包数"
    }
   ]
  }
 ]
}